# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdlistChild', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Parent',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='username',
            new_name='tdlistParent',
        ),
        migrations.AddField(
            model_name='child',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolistapp.Parent'),
        ),
    ]
