# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_auto_20170312_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='complete',
            field=models.NullBooleanField(),
        ),
    ]
